on:
 push:
  branches: [master]
name: Publish Website over SFTP
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://versenydonto.nisz.hu:10029/
        ftp-username: vuser_1
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        git-ftp-args: --insecure --remote-root /var/www/html # if your certificate is setup correctly this can be removed (see known-hosts argument)
  Discord-Notif:
     name: Discord notifications
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@master
      - name: Slack Notification Demo
        uses: bryan-nice/slack-notification@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'Új verzió éles!'
          SLACK_MESSAGE: 'Sikeres publikálás!'
